[project]
name = "genai-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=1.99.1",
    "tiktoken>=0.10.0",
]

[tool.uv.workspace]
members = [
    "projects/persona-project",
]
